version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - .env

  web:
    build: .
    command: bash -c "
        python manage.py migrate && 
        python manage.py populate_food_trucks food-truck-data.csv &&
        python manage.py test &&
        python manage.py runserver 0.0.0.0:8000"
        
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure

networks:
  custom_network:
    driver: bridge
