# Generated by Django 4.2.7 on 2023-11-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruckInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=100)),
                ('cnn', models.IntegerField()),
                ('location_description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('block_lot', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=50)),
                ('lot', models.CharField(max_length=50)),
                ('permit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('food_items', models.TextField()),
                ('x_coordinates', models.DecimalField(decimal_places=10, max_digits=18)),
                ('y_coordinates', models.DecimalField(decimal_places=10, max_digits=18)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('schedule', models.TextField()),
                ('days_hours', models.TextField(blank=True, null=True)),
                ('noi_sent', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.CharField(blank=True, max_length=255, null=True)),
                ('received', models.DateField(blank=True, null=True)),
                ('prior_permit', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('fire_prevention_districts', models.IntegerField()),
                ('police_districts', models.IntegerField()),
                ('supervisor_districts', models.IntegerField()),
                ('zip_codes', models.IntegerField()),
                ('neighborhoods_old', models.IntegerField()),
            ],
        ),
    ]
